name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - run: swift --version
      - run: swift build
      - run: swift test

  test-linux:
    runs-on: ubuntu-latest
    container: swift:5.10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - run: swift --version
      - run: swift build
      - run: swift test
